language: node_js
node_js:
  - 8
  - 10
  - 12

script:
  - npm run cover-test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7937aa9d2e9d767d0421
    on_success: always
    on_failure: always
